<script setup lang="ts">
import type { AiAnswer, DisclosureOutcome, SteamAuditPublicRecord } from '~/types/steam-audit'
import { computed, ref } from 'vue'

const props = defineProps<{
  record: SteamAuditPublicRecord
}>()

const popupBlocked = ref(false)

const ANSWER_LABEL: Record<AiAnswer, string> = {
  none: 'No AI',
  dev_only: 'Dev only (not shipped)',
  shipped_pre: 'Ships — pre-generated',
  shipped_live: 'Live at runtime',
  unsure: 'Unsure',
}

const OUTCOME_LABEL: Record<DisclosureOutcome, string> = {
  none: '—',
  exempt: 'Exempt',
  pre: 'Disclose · Pre-Generated',
  live: 'Disclose · Live-Generated',
  gray: 'Gray zone',
}

const generatedDate = computed(() => {
  const d = new Date(props.record.createdAt)
  return Number.isNaN(d.getTime()) ? props.record.createdAt : d.toISOString().slice(0, 10)
})

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// Build a standalone, print-optimised document and let the browser save it as
// PDF. No new dependency, no inline script in the child window.
function downloadPdf() {
  const r = props.record
  const rows = r.classification.perCategory.map(c => `
    <tr>
      <td>${escapeHtml(c.label)}</td>
      <td>${escapeHtml(ANSWER_LABEL[c.answer])}</td>
      <td>${escapeHtml(OUTCOME_LABEL[c.outcome])}</td>
      <td>${escapeHtml(c.rationale)}${c.flag ? `<br><em>${escapeHtml(c.flag)}</em>` : ''}</td>
    </tr>`).join('')

  const texts = r.result
    ? `
      <h2>Disclosure text on record</h2>
      ${r.result.preGeneratedText ? `<h3>Pre-Generated AI Content</h3><p>${escapeHtml(r.result.preGeneratedText)}</p>` : ''}
      ${r.result.liveGeneratedText ? `<h3>Live-Generated AI Content</h3><p>${escapeHtml(r.result.liveGeneratedText)}</p>` : ''}
      ${r.result.liveGuardrailsText ? `<h3>Guardrails</h3><p>${escapeHtml(r.result.liveGuardrailsText)}</p>` : ''}
      ${r.result.storePublicText ? `<h3>Store-page disclosure</h3><p>${escapeHtml(r.result.storePublicText)}</p>` : ''}`
    : ''

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Steam AI Disclosure Protocol</title>
    <style>
      body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #0f172a; line-height: 1.5; max-width: 760px; margin: 32px auto; padding: 0 24px; }
      h1 { font-size: 20px; margin: 0 0 4px; }
      h2 { font-size: 15px; margin: 28px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
      h3 { font-size: 13px; margin: 14px 0 2px; }
      .meta { color: #64748b; font-size: 12px; margin-bottom: 16px; }
      table { width: 100%; border-collapse: collapse; font-size: 12px; }
      th, td { border: 1px solid #e2e8f0; padding: 6px 8px; text-align: left; vertical-align: top; }
      th { background: #f1f5f9; }
      p { font-size: 13px; }
      footer { margin-top: 28px; color: #94a3b8; font-size: 11px; border-top: 1px solid #e2e8f0; padding-top: 8px; }
    </style></head><body>
    <h1>Steam AI Disclosure — Compliance Protocol</h1>
    <div class="meta">
      ${r.gameName ? `Game: <strong>${escapeHtml(r.gameName)}</strong> · ` : ''}
      Generated ${generatedDate.value} · Valve policy v${escapeHtml(r.rulesetVersion)} · ref ${escapeHtml(r.id)}
    </div>
    <h2>Determination by category</h2>
    <table>
      <thead><tr><th>Category</th><th>Your answer</th><th>Determination</th><th>Rationale</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    ${texts}
    <footer>Generated by ravy.pro. Informational good-faith documentation of an AI-content disclosure review against the stated Valve policy version. Not legal advice.</footer>
    </body></html>`

  const w = window.open('', '_blank')
  if (!w) {
    popupBlocked.value = true
    return
  }
  popupBlocked.value = false
  w.document.write(html)
  w.document.close()
  w.focus()
  w.print()
}
</script>

<template>
  <div class="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden">
    <header class="flex items-start justify-between gap-3 px-5 py-4 border-b border-slate-100 dark:border-slate-800">
      <div>
        <h3 class="font-semibold text-slate-900 dark:text-slate-100">
          Compliance protocol
        </h3>
        <p class="mt-0.5 eyebrow">
          {{ record.gameName ? `${record.gameName} · ` : '' }}{{ generatedDate }} · v{{ record.rulesetVersion }}
        </p>
      </div>
      <button
        type="button"
        class="shrink-0 inline-flex items-center gap-1.5 rounded-md bg-slate-900 dark:bg-white text-white dark:text-slate-900 px-3.5 py-1.5 text-sm font-medium hover:opacity-90 hover:cursor-pointer transition"
        @click="downloadPdf"
      >
        <Icon name="mdi:file-download-outline" class="w-4 h-4" />
        Download PDF
      </button>
    </header>

    <div class="px-5 py-4 overflow-x-auto">
      <table class="w-full text-sm border-collapse">
        <thead>
          <tr class="text-left text-slate-500 dark:text-slate-400">
            <th class="py-2 pr-3 font-medium">
              Category
            </th>
            <th class="py-2 pr-3 font-medium">
              Your answer
            </th>
            <th class="py-2 font-medium">
              Determination
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="c in record.classification.perCategory" :key="c.id" class="border-t border-slate-100 dark:border-slate-800 align-top">
            <td class="py-2 pr-3 text-slate-700 dark:text-slate-200">
              {{ c.label }}
            </td>
            <td class="py-2 pr-3 text-slate-500 dark:text-slate-400 font-spacemono text-xs">
              {{ ANSWER_LABEL[c.answer] }}
            </td>
            <td class="py-2 text-slate-700 dark:text-slate-200">
              {{ OUTCOME_LABEL[c.outcome] }}
            </td>
          </tr>
        </tbody>
      </table>
      <p v-if="popupBlocked" class="mt-3 text-sm text-amber-600 dark:text-amber-400">
        Your browser blocked the print window. Allow pop-ups for this site, then tap Download PDF again.
      </p>
      <p class="mt-4 text-xs text-slate-400 leading-relaxed">
        This dated record documents your good-faith review against Valve policy v{{ record.rulesetVersion }}. Keep it in case of a report or rule change. Informational, not legal advice.
      </p>
    </div>
  </div>
</template>
