import type { H3Event } from 'h3'
import type {
  SteamAuditClassification,
  SteamAuditPublicRecord,
  SteamAuditRecord,
  SteamAuditResult,
} from '~~/types/steam-audit'
import { getQuery } from 'h3'
import { seoData } from '~~/data'
import { sendResultEmail } from './email'
import { getDb } from './firebase-admin'
import { signAccessToken, verifyAccessToken } from './steam-audit-token'
import { getStripe } from './stripe'

const COLLECTION = 'steam_ai_audits'

export interface GenerationConfig {
  openaiApiKey: string
  resendApiKey: string
  tokenSecret: string
}

function nowIso(): string {
  return new Date().toISOString()
}

export function steamAuditCollection() {
  return getDb().collection(COLLECTION)
}

async function updateAudit(id: string, patch: Record<string, unknown>) {
  await steamAuditCollection().doc(id).set({ ...patch, updatedAt: nowIso() }, { merge: true })
}

// Strip Stripe/email internals before anything reaches the browser.
export function toPublicRecord(id: string, data: SteamAuditRecord): SteamAuditPublicRecord {
  return {
    id,
    status: data.status,
    progress: data.progress,
    step: data.step,
    gameName: data.gameName,
    rulesetVersion: data.rulesetVersion,
    classification: data.classification,
    result: data.result,
    error: data.error,
    createdAt: data.createdAt,
    updatedAt: data.updatedAt,
  }
}

function extractTextFromResponse(payload: Record<string, unknown>): string {
  const top = payload.output_text
  if (typeof top === 'string' && top.trim())
    return top

  const output = Array.isArray(payload.output) ? payload.output : []
  const chunks: string[] = []
  for (const item of output) {
    const itemObj = item as Record<string, unknown>
    const content = Array.isArray(itemObj.content) ? itemObj.content : []
    for (const c of content) {
      const cObj = c as Record<string, unknown>
      if (typeof cObj.text === 'string' && cObj.text.trim())
        chunks.push(cObj.text)
    }
  }
  return chunks.join('\n').trim()
}

function buildPrompt(classification: SteamAuditClassification, gameName?: string): string {
  const game = gameName ? `Game title: "${gameName}".` : 'No game title provided.'
  const lines = classification.perCategory
    .map(c => `- ${c.label}: ${c.outcome} (developer answered: ${c.answer})`)
    .join('\n')

  return `
You are helping a game developer fill in Valve's Steamworks "Generative AI Content" disclosure for the Steam store page.

${game}

How Valve splits disclosure:
- Pre-Generated AI Content: AI-assisted content created during development that ships in the build and is consumed by players.
- Live-Generated AI Content: content generated by AI while the game runs. Valve additionally requires a description of the guardrails that prevent it from generating illegal content.
- Behind-the-scenes efficiency tools (e.g. AI coding assistants) are NOT disclosed.

A deterministic classifier already decided each category. Trust it; do not re-classify:
${lines}

Write concise, honest, professional text. Rules:
- preGeneratedText: cover ONLY categories classified "pre". One short paragraph describing what AI helped create and how. If there are no "pre" categories, return "".
- liveGeneratedText: cover ONLY categories classified "live". If none, return "".
- liveGuardrailsText: if any "live" category exists, describe reasonable guardrails (output filtering, restricting generation scope, moderation, blocking illegal content). If no "live", return "".
- storePublicText: a short, calm player-facing note for the store page summarising AI use, worded to minimise community backlash and avoid over-claiming. If nothing is disclosed, return a single honest line stating the game does not ship AI-generated content consumed by players.
- perCategoryRationale: for each category classified "pre", "live" or "gray", one short note the developer can keep for their records (use the category label as "category").
- communityPhrasingNotes: 2-4 short, practical tips on wording the public disclosure to stay accurate and reduce backlash.

Do not provide legal advice. Do not invent AI usage beyond the classification. Keep it factual and tight.
`.trim()
}

const RESULT_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    preGeneratedText: { type: 'string' },
    liveGeneratedText: { type: 'string' },
    liveGuardrailsText: { type: 'string' },
    storePublicText: { type: 'string' },
    perCategoryRationale: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          category: { type: 'string' },
          note: { type: 'string' },
        },
        required: ['category', 'note'],
      },
    },
    communityPhrasingNotes: {
      type: 'array',
      items: { type: 'string' },
    },
  },
  required: ['preGeneratedText', 'liveGeneratedText', 'liveGuardrailsText', 'storePublicText', 'perCategoryRationale', 'communityPhrasingNotes'],
}

function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

// Calls OpenAI with transient-error retries (network failures, 429, 5xx, or an
// empty body). Non-retryable 4xx and the final attempt propagate the error.
async function requestDisclosureText(prompt: string, openaiApiKey: string): Promise<string> {
  const maxAttempts = 3
  let lastError: unknown

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    let response: Response
    try {
      response = await fetch('https://api.openai.com/v1/responses', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${openaiApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'gpt-5-mini',
          input: prompt,
          text: {
            format: {
              type: 'json_schema',
              name: 'steam_ai_disclosure',
              schema: RESULT_SCHEMA,
            },
          },
        }),
      })
    }
    catch (netErr) {
      lastError = netErr
      if (attempt < maxAttempts) {
        await delay(attempt * 800)
        continue
      }
      throw netErr
    }

    if (!response.ok) {
      const body = await response.text()
      if ((response.status === 429 || response.status >= 500) && attempt < maxAttempts) {
        lastError = new Error(`OpenAI ${response.status}`)
        await delay(attempt * 800)
        continue
      }
      throw new Error(`OpenAI request failed (${response.status}): ${body}`)
    }

    const payload = await response.json() as Record<string, unknown>
    const rawText = extractTextFromResponse(payload)
    if (!rawText) {
      if (attempt < maxAttempts) {
        lastError = new Error('OpenAI returned an empty body')
        await delay(attempt * 800)
        continue
      }
      throw new Error('OpenAI response did not contain text output')
    }

    return rawText
  }

  throw lastError instanceof Error ? lastError : new Error('OpenAI request failed')
}

export async function processSteamAuditGeneration(
  id: string,
  classification: SteamAuditClassification,
  gameName: string | undefined,
  openaiApiKey: string,
): Promise<void> {
  try {
    if (!openaiApiKey)
      throw new Error('OpenAI API key is not configured')

    await updateAudit(id, { status: 'processing', progress: 35, step: 'Writing disclosure text' })

    const rawText = await requestDisclosureText(buildPrompt(classification, gameName), openaiApiKey)

    await updateAudit(id, { progress: 80, step: 'Formatting your pack' })
    const normalized = rawText
      .replace(/^```json\s*/, '')
      .replace(/^```\s*/, '')
      .replace(/\s*```$/, '')
      .trim()

    const result = JSON.parse(normalized) as SteamAuditResult

    await updateAudit(id, { status: 'done', progress: 100, step: 'Completed', result })
  }
  catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Generation failed'
    await updateAudit(id, { status: 'error', progress: 100, step: 'Failed', error: message })
    throw new Error(message)
  }
}

// Called from the Stripe webhook. Idempotent: only the first transition out of
// `awaiting_payment` triggers generation. Returns quickly — generation + email
// run fire-and-forget so the webhook can ack Stripe fast.
export async function markPaidAndGenerate(
  id: string,
  email: string | undefined,
  sessionId: string,
  config: GenerationConfig,
): Promise<void> {
  const ref = steamAuditCollection().doc(id)
  const snap = await ref.get()
  if (!snap.exists)
    return
  const data = snap.data() as SteamAuditRecord
  if (data.status !== 'awaiting_payment')
    return // already handled — idempotent

  const patch: Record<string, unknown> = {
    status: 'paid',
    stripeSessionId: sessionId,
    paidAt: nowIso(),
    progress: 10,
    step: 'Payment received',
    updatedAt: nowIso(),
  }
  if (email)
    patch.customerEmail = email.toLowerCase()
  await ref.set(patch, { merge: true })

  void runGenerationThenEmail(id, config).catch((err) => {
    console.error('Steam audit generation failed', err)
  })
}

async function runGenerationThenEmail(id: string, config: GenerationConfig): Promise<void> {
  const ref = steamAuditCollection().doc(id)
  const before = (await ref.get()).data() as SteamAuditRecord | undefined
  if (!before)
    return

  await processSteamAuditGeneration(id, before.classification, before.gameName, config.openaiApiKey)

  const after = (await ref.get()).data() as SteamAuditRecord | undefined
  if (after?.status === 'done' && after.customerEmail && config.resendApiKey && config.tokenSecret) {
    try {
      const token = await signAccessToken(id, config.tokenSecret)
      const origin = seoData.mySite.replace(/\/+$/, '')
      const url = `${origin}/tools/steam-ai-disclosure/result/${id}?t=${token}`
      await sendResultEmail({ to: after.customerEmail, url, gameName: after.gameName, apiKey: config.resendApiKey })
    }
    catch (err) {
      console.error('Steam audit result email failed', err)
    }
  }
}

export async function getAuditRecord(id: string): Promise<SteamAuditRecord | null> {
  const snap = await steamAuditCollection().doc(id).get()
  if (!snap.exists)
    return null
  return snap.data() as SteamAuditRecord
}

// Shared authorisation for the result + retry endpoints: a valid signed token
// (?t=) OR a Stripe checkout session_id that paid for this exact audit.
export async function authorizeAuditAccess(event: H3Event, id: string): Promise<boolean> {
  const config = useRuntimeConfig(event)
  const query = getQuery(event)

  const token = typeof query.t === 'string' ? query.t : ''
  if (token && (await verifyAccessToken(token, config.steamAuditTokenSecret)) === id)
    return true

  if (typeof query.session_id === 'string' && query.session_id) {
    try {
      const stripe = getStripe(event)
      const session = await stripe.checkout.sessions.retrieve(query.session_id)
      if (session.payment_status === 'paid' && session.metadata?.auditId === id)
        return true
    }
    catch {
      // invalid session — not authorized
    }
  }

  return false
}

function olderThan(iso: string, ms: number): boolean {
  return Date.now() - new Date(iso).getTime() > ms
}

export type RetryStatus = 'not_found' | 'unpaid' | 'done' | 'in_progress' | 'retrying'

// Re-runs generation for an already-paid audit (no new charge — it reuses the
// stored classification). Safe to call on a stuck/errored audit; skips when a
// generation looks genuinely in flight.
export async function retryGeneration(id: string, config: GenerationConfig): Promise<RetryStatus> {
  const data = await getAuditRecord(id)
  if (!data)
    return 'not_found'
  if (data.status === 'awaiting_payment')
    return 'unpaid'
  if (data.status === 'done')
    return 'done'
  if (data.status === 'processing' && !olderThan(data.updatedAt, 45_000))
    return 'in_progress'

  void runGenerationThenEmail(id, config).catch((err) => {
    console.error('Steam audit retry failed', err)
  })
  return 'retrying'
}
